export class TicketForm{
        ticketid:string;
		 ticket_date:string;
         username:string;
         name:string;
		 request_type:string;
		 priority:string;
		 travel_city:string;
		 from_city:string;
		 travel_start_date:Date;
		 travel_end_date:Date;
		 passport_number:string;
		 project_name:string;
		 expense_borne_by:string;
		 travel_approver_name:string;
		 expected_duration:string;
		 upper_bound_cost:string;
		 additional_details:string;
         status:string;
         constructor(       
            ticketid?:string,
            ticket_date?:string,
            username?:string,
            name?:string,
            request_type?:string,
            priority?:string,
            travel_city?:string,
            from_city?:string,
            travel_start_date?:Date,
            travel_end_date?:Date,
            passport_number?:string,
            project_name?:string,
            expense_borne_by?:string,
            travel_approver_name?:string,
            expected_duration?:string,
            upper_bound_cost?:string,
            additional_details?:string,
            status?:string ){
                this.ticketid=ticketid,
                this.ticket_date=ticket_date,
                this.username=username,
                this.name=name,
                this.request_type=request_type,
                this.priority=priority,
                this.travel_city=travel_city,
                this.from_city=from_city,
                this.travel_start_date=travel_start_date,
                this.travel_end_date=travel_end_date,
                this.passport_number=passport_number,
                this.project_name=project_name,
                this.expense_borne_by=expense_borne_by,
                this.travel_approver_name=travel_approver_name,
                this.expected_duration=expected_duration,
                this.upper_bound_cost=upper_bound_cost,
                this.additional_details=additional_details,
                this.status=status
            }
}